export const t={
    first_name:"שם פרט",
    last_name: "שם משפחה",
    father_name: "שם האב",
    vip: "vip",
    allowed: "חבר",
    joined_date:"תאריך הצטרפות",
    manager_permissions: "הרשאות מנהל",
    scoring: "ניקוד",
    status: "סטטוס",
    statusReason: "סיבת הסטטוס",
    street:"רחוב",
    num_street:"מספר רחוב",
    house:"בית",
    city:"עיר",
    phon:"טלפון",
    phon2:"טלפון2",
    email:"איימל",
    maritalStatus:"מצב אישי",
}