export const t:any = {
    first_name: "שם פרט",
    last_name: "שם משפחה",
    father_name: "שם האב",
    vip: "vip",
    _id:"קוד",
    allowed: "חבר",
    joined_date: "תאריך הצטרפות",
    manager_permissions: "הרשאות מנהל",
    scoring: "ניקוד",
    status: "סטטוס",
    statusReason: "סיבת הסטטוס",
    street: "רחוב",
    num_street: "מספר רחוב",
    house: "בית",
    city: "עיר",
    phon: "טלפון",
    phon2: "טלפון2",
    email: "איימל",
    maritalStatus: "מצב אישי",
    add: "הוסף",
    edit: "ערוך",
    addDeposit: "הוסף הפקדה",
    addWithdrawal: "הוסף משיכה",
    addLoan: "הוסף הלוואה",
    Withdrawals: "משיכות",
    Deposits: "הפקדות",
    updatedAt:"עדכון אחרון",
    DateOfBirth:"תאריך לידה",
    createdAt:"תאריך יצרה",
    tz:'ת"ז',
    funds:'קרנות',
    futureWithdrawals:"משיכות עתדיות",
    fundName:'שם קרן',
    amount:'סה"כ'

}